#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


echo "Migrating"
python manage.py migrate

echo "INIT Data"
python manage.py runscript initialise

echo "Launching the application....."
exec uvicorn config.asgi:application --host 0.0.0.0 --reload --reload-include '*.html'
